env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - FRAMEWORK_NAME=ValidationNEL
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.3
      script:
        - pod lib lint
    - os: osx
      language: objective-c
      osx_image: xcode7.3
      script:
        # rebuild frameworks if Cartfile.resolved is changed from last build
        - sh bin/bootstrap-if-needed
        - sh bin/ci
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'ValidationNEL'
      cache:
        directories:
          - Carthage/Build