env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - FRAMEWORK_NAME=ValidationNEL
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.3
      script:
        - pod lib lint
    - os: osx
      language: objective-c
      osx_image: xcode7.3
      before_install:
        - git submodule update --init --recursive
      script:
        # - carthage build --no-skip-current
        - sh bin/ci
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'ValidationNEL'
before_cache:
  - bin/bootstrap-if-needed
cache:
  directories:
    - Carthage/Build
    - Carthage/Cartfile.resolved