language: objective-c
osx_image: xcode7.3
git:
  submodules: false
env:
  global:
  - FRAMEWORK_NAME=ValidationNEL
script:
  - carthage bootstrap
  - sh bin/ci
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'ValidationNEL'
