env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - FRAMEWORK_NAME=ValidationNEL
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode7.3
      script:
        - pod lib lint
    - os: osx
      language: objective-c
      osx_image: xcode7.3
      before_install:
        - brew update
        - brew outdated carthage || brew upgrade carthage
      script:
        # rebuild frameworks if Cartfile.resolved is changed from last build
        - sh bin/bootstrap-if-needed
        - sh bin/ci
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'ValidationNEL'
      cache:
        directories:
          - Carthage/Build
      before_deploy:
        - carthage build --no-skip-current
        - carthage archive $FRAMEWORK_NAME
      deploy:
        provider: releases
        api_key:
          secure: DpMEwhskvDdD86ippGTDFtj4EsLet6As4zC0xR3TrEpQx6QPEwnKgKCkW8gyMlDndOYPHoSiPCn046zMLWPfSPnl7ihqhOos/khws/vZvjA7oiwUEW6ujTxvngrosMxoDOOeJGoA6lCUf232R+kgKBpOVkTdscAfjh9BrTkeTlCGhAxY/tk/vjoA6fRpx+tYNcIRu1mA8oWKlqpOv8WZVN0A/gCr3siTrZHdFLJ8MW7mw4bsI/S9SZQfnlrfUDWCp6FOGM69QgHpd7Zo5JgVAjBowmzOYvodtWMKZlotTrRVSoIN6sTRCTyr8bHn6mMYi6ItMx5nkNvnW+DQKEdMVGE3X2kHZY1B+5eDz2/vpq5EhaNVLnY3DZjAnSYC9RlgYsWYz1Wek6MzNyphP5W4KO+YEfG6imB04ZrSqJd5a0ZXRYnBSKSu/QQnAa55BJESdHepZTXS5kuTWihUVZghC4zfirQLIRvAYOVOFoI3ZqMVc61x2pzGnl/NjLuqEGSB/NtLQ/gznMYaCIKOGEJc9J7ZBAa1qNvCqSA33hLzV7DpAAOXutStPJkCJ8qiICX2HTR4hW8WdF64CLr0ng1WcXk+ChV0XfC/Qdm6PD/Mw9uPV9xp8g98Mr9IukGdgQUco+1UMbhdB4MOukV7txFXlNSn/5ZoWPdnN3PXMN4I4c8=
        file: ValidationNEL.framework.zip
        skip_cleanup: true
        on:
          repo: Hxucaa/ValidationNEL
          tags: true